#!/bin/bash

echo "Creating class files $1"

cat >> $1.class.hpp << HEREDOC
#pragma once

class $1 {
public:
    $1(void);
    $1(const $1 &src);
    ~$1(void);

    $1 &operator= (const $1 &rhs);
};
HEREDOC

cat >> $1.class.cpp << HEREDOC
#include "$1.class.hpp"

$1::$1(void) {}

$1::$1(const $1 &src) {}

$1::~$1(void) {}

$1 & $1::operator= (const $1 &rhs) {
    return *this;
}
HEREDOC