#!/bin/bash

echo "Creating Makefile for project $1"
CPP_FILES=$(find . -type f -follow -print | grep "\.cpp" | grep -v '.swp')
CPP_FILES=${CPP_FILES//[$'\n']/\\$'\n'}

read -r -d '' content << HEREDOC
NAME = $1

CPP_FILES = $CPP_FILES

O_FILES = \$(CPP_FILES:%.cpp=%.o)

CC = clang++
FLAGS = -Wall -Werror -Wextra

all: \$(NAME)

\$(NAME): \$(O_FILES)
	\$(CC) \$(FLAGS) \$^ \$(INCLUDES) -o \$@

%.o: %.cpp
	\$(CC) \$(FLAGS) \$(INCLUDES) -o \$@ -c \$<

clean:
	rm -f \$(O_FILES)

fclean: clean
	rm -f \$(NAME)

re: fclean all

.PHONY: clean all fclean re
HEREDOC

printf "%s\n" "$content" > Makefile
